export default actionTypes = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    GET_CART_ITEMS: "GET_CART_ITEMS",
    SET_CART_TOTAL: "SET_CART_TOTAL",
    SET_ACTIVE_PRODUCT: "SET_ACTIVE_PRODUCT",
    GET_ACTIVE_PRODUCT: "GET_ACTIVE_PRODUCT",
    GET_WALLET_INFO: "GET_WALLET_INFO",
    SET_WALLET_INFO: "SET_WALLET_INFO",
    SET_TODAY_FOODS: "SET_TODAY_FOODS",
    GET_TODAY_FOODS: "GET_TODAY_FOODS",
}